export * from "./about-hero"
export * from "./about-info"
export * from "./contacts-details"
export * from "./footer-about"
export * from "./footer-contacts"
export * from "./header-contacts"
export * from "./main-page-hero"
export * from "./main-page-services"
